### ISSUE TITLE
ts lib change broke existing usages

### ISSUE THREAD

**Issue by simoneb** [SamVerschueren/tsd#101]
Upgrading from 0.14.0 to 0.15.1 broke the usage of tsd in [this repository](https://github.com/nearform/sql/pull/57), without any apparently good reason. I have narrowed it down to [this change](https://github.com/SamVerschueren/tsd/commit/f5b69ed20d8393655dca501088f229b519afc0ad#diff-e717ee248865fa4044ef4561e4692693459eb15f9c1605b12ca42b8f38226fa3L37-R37).

I'm not sure exactly what is the right syntax here but the new library names don't seem to work for us. The documentation seems to suggest that the new names are right (assuming they're case insensitive): https://www.typescriptlang.org/tsconfig#lib.

Yet the link to the source code shows that the lib names are different and that using one of those file names, as it was before the changed linked above, actually makes it work.

**Comment by bendrucker** [comment]
See #100
