### ISSUE TITLE
The override keyword does not work

### ISSUE THREAD

**Issue by sounisi5011** [SamVerschueren/tsd#106]
In TypeScript 4.3, [a new feature, the `override` keyword, has been added](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#override).
However, currently tsd does not process the `override` keyword correctly.

I have tried to use the `override` keyword in the following project:

* https://github.com/sounisi5011/npm-packages/blob/f410ba686a29118beacde026e15d59a814626f8e/packages/stream-transform-from/src/index.ts#L109-L131

However, the following error occurs:

```
  src/index.ts:109:4
  ✖  109:4   Member override implicitly has an any type.  
  ✖  109:13  ; expected.                                  
  ✖  122:4   Duplicate identifier override.               
  ✖  122:13  ; expected.                                  

  4 errors
```
https://github.com/sounisi5011/npm-packages/runs/2685162070#step:9:232

**Comment by BendingBender** [comment]
Yeah, this is due to the fact that `tsd` is still based on `typescript@4.2`. We'll have to bump the `typescript` dependency for this to work.

**Comment by sounisi5011** [comment]
With the [upgrade to `tsd@0.16.0`](https://github.com/sounisi5011/npm-packages/pull/111), I can now use the `override` keyword! Thank you.
