### ISSUE TITLE
error while useing pnp / yarn v2 (berry)

### ISSUE THREAD

**Issue by mathe42** [SamVerschueren/tsd#111]
I get some Errors:

```
  ✖    1:31  Cannot find module lit or its corresponding type declarations.
  ✖    2:31  Cannot find module lit or its corresponding type declarations.
  ✖  189:14  Cannot find module @vue/reactivity or its corresponding type declarations.
  ✖  190:14  Cannot find module lit or its corresponding type declarations.
```

I use yarn v2 with pnp.

No problem with `tsc` / typescript.

Any thoughts on how to solve it?

**Comment by sindresorhus** [comment]
Does `tsd` work fine when installing with npm? If yes, then it's a Yarn v2 problem and should be reported over at https://github.com/yarnpkg/berry instead.

**Comment by mathe42** [comment]
Somehow it works now... Strange... :/

**Comment by erikbrinkman** [comment]
Ran into this, and checked on yarn. It was posted there and they [mentioned](https://github.com/yarnpkg/berry/issues/3394#issuecomment-914156599) it being an issue with tsd's internally bundled typescript. I'm not familiar with the way that tsd uses it's included typescript, but does that at least warrant opening this back up, or is your stance that pnp should be able to handle resolution in that scenario?

**Comment by erikbrinkman** [comment]
I've since found `@yarnpkg/pnpify` that allows this to work, so it can safely stay closed.

**Comment by xyy94813** [comment]
@yarnpkg/pnpify with tsd is not working for me...

Node version: v20.10.0
Yarn version: 4.1.0
tsd version: 0.30.7

```sh
yarn dlx @yarnpkg/pnpify tsd --files ./types/**/*.test-d.ts
```

got error: 
```sh
Internal Error: spawn tsd ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
