### ISSUE TITLE
JSX .tsx support

### ISSUE THREAD

**Issue by fregante** [SamVerschueren/tsd#15]
```tsx
// index.test-d.tsx
import {expectType} from 'tsd-check';
import React from 'dom-chef';

expectType<HTMLDivElement>(<div/>);
```

**Comment by SamVerschueren** [comment]
I'm really not familiar with .tsx. Is the only thing we should do is check if it's a `index.test-d.tsx` or a `index.test-d.ts` is present?

A failing test for this would be nice as would allow me to fix it more easily and make sure I don't misunderstand the problem :).

**Comment by sindresorhus** [comment]
> Is the only thing we should do is check if it's a index.test-d.tsx or a index.test-d.ts is present?

Correct:

> In order to use JSX you must do two things.
> 1. Name your files with a .tsx extension
> 2. Enable the jsx option
>
> \- https://www.typescriptlang.org/docs/handbook/jsx.html

**Comment by bfred-it** [comment]
Also, disregard my first example because dom-chef types aren't there yet.

This should be your test, _I think:_

```js
// index.test-d.tsx
import {expectType} from 'tsd-check';
import React from 'react';

function Welcome(props) {
  return <h1>Hello, {props.name}</h1>;
}

expectType<Welcome>(<Welcome/>);
```

**Comment by sindresorhus** [comment]
It's really stupid that we're forced to use a `.tsx` extension, but that's how it is until https://github.com/Microsoft/TypeScript/issues/30503 is resolved.

**Comment by SamVerschueren** [comment]
Thanks @bfred-it for the test case! I'll see what I can do.

**Comment by SamVerschueren** [comment]
I tried looking into this, but not sure if I understand the problem correctly.

The thing is that the `expectType` in your example will never throw.

```tsx
class Welcome extends React.Component() {
	constructor() {
		super();
		return <h1>Hello</h1>;
	}
}

class Unicorn extends React.Component() {
	constructor() {
		super();
		return <h2>Unicorn</h2>;
	}
}

expectType<Welcome>(<Unicorn/>);
```

The reason is that `<Unicorn />` is of type `any` in TypeScript.

So my question actually is, why do we need `tsd` to pick up `test-d.tsx` files? For example, if I look at the typings of [`dom-chef`](https://github.com/vadimdemedes/dom-chef/blob/master/index.d.ts), I don't see a reason why the test for that type definition should have a `tsx` file extension? What kind of tsd test could be written that it has to be `.tsx`?

I'm just wondering and clarifying so that we are all on the same page :). I could totally add it for convenience, but I want to know the 'why'.

**Comment by bfred-it** [comment]
If you enable JSX in TypeScript the type will be `JSX.Element`

**Comment by SamVerschueren** [comment]
This is what I get

![image](https://user-images.githubusercontent.com/1913805/64972529-bdfc1e00-d8a9-11e9-8df2-8fd4d20a2dd5.png)

Even a simple `<div />` element doesn't work...

![image](https://user-images.githubusercontent.com/1913805/64972530-bdfc1e00-d8a9-11e9-8c4d-1648bc2bc2b9.png)

I must be missing something I guess :thinking_face:

**Comment by SamVerschueren** [comment]
On a sidenote, I installed `@types/react`. Is that necessary?

**Comment by fregante** [comment]
Yeah, JSX types are awful, The `type 'Element'` it's referring to is not the browser's `Element` but `JSX.Element` specifically. So that should probably be:

```tsx
expectType<JSX.Element>(<div/>);
```

I made a mistake in my OP

**Comment by fregante** [comment]
Even in that case I'm not entirely sure that `<div/>` will work. In Refined GitHub we also have this:

https://github.com/sindresorhus/refined-github/blob/6631e5f351781e714e6eb3c6af24d76a6af301e7/source/globals.d.ts#L40-L52

**Comment by SamVerschueren** [comment]
But what to do in case of `Unicorn`? We can't really type check that, right?

```ts
class Unicorn extends React.Component {
	constructor(props) {
		super(props);
	}

	render() {
		return <h1>Unicorn</h1>;
	}
}

expectType<Unicorn>(<Unicorn />);
```

Or would it be enough that `tsd` just picks up `tsx` files? If that's the case, I think it works right now (on my machine :p).

**Comment by fregante** [comment]
I think technically `<Unicorn />` isn't of type `Unicorn` but whatever `React.createElement(Unicorn)` maps to, which appears to be `React.ComponentElement<{}, Unicorn>`

Also:

```ts
React.createElement('div');
// appears to be of type
React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>`
```

**Comment by SamVerschueren** [comment]
For some reason, this doesn't fail. 

```ts
expectType<React.ComponentElement<{}, Welcome>>(<Unicorn />);
expectType<React.ComponentElement<{}, Welcome>>(React.createElement(Unicorn));
```

Let's just enable this feature and see how it goes. `tsd` can't help it if the JSX or React type definitions are bad. As long as it picks up the `tsx`/`jsx` files, we're good to go. It's really a small change in the codebase.

**Comment by SamVerschueren** [comment]
I could use some help testing https://github.com/SamVerschueren/tsd/pull/36 to see if this is what is expected :).

**Comment by SamVerschueren** [comment]
Released as `0.8.0`

**Comment by fregante** [comment]
Thank you ☺️

**Comment by SamVerschueren** [comment]
Thank you for opening the issue and helping me understand the problem :)
