### ISSUE TITLE
`printType` does not print anything

### ISSUE THREAD

**Issue by RobinTail** [SamVerschueren/tsd#171]
Could you help me to figure out how properly to use this method?
Since in my case the following line does not print anything:

```ts
printType(123)
```

Should it write to console or which behavior is intended? 
Thank you

**Comment by tommy-mitchell** [comment]
`printType` reports the type of an expression to the console when running `tsd` (e.g. `npx tsd`)

**Comment by RobinTail** [comment]
thank you
