### ISSUE TITLE
Output test success

### ISSUE THREAD

**Issue by Ethan-Arrowood** [SamVerschueren/tsd#23]
Right now when I run `npx tsd` on a file, if all the tests pass, nothing is output to the console. I would like for either a check-like view for each assertion or at least a counter of how many tests passed in total. 

FYI: I've been working on a major [type refactor](https://github.com/fastify/fastify/pull/1569) for [`fastify`](https://fastify.io) and I'm using this library to test my new types 😄

**Comment by sindresorhus** [comment]
I prefer silent on success and loud on failure.

**Comment by BendingBender** [comment]
It's actually not that easy to count. What should be considered a test? We have explicit assertions (`expectType`/`expectError`) but also surrounding code.

- If there's an error in the surrounding code, does this count as a test failure?
- If everything is OK, should we count every line of code? Every statement?
- Should we count file-wise?

We don't really have a notion of test cases in this module. Of course it's possible to introduce some kind of test API but is it really worth it?

**Comment by Ethan-Arrowood** [comment]
Okay sounds good!
