### ISSUE TITLE
Doesn't catch missing imports

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/tsd#24]
See https://github.com/sindresorhus/type-fest/pull/29

**Comment by sindresorhus** [comment]
This happened again: https://github.com/sindresorhus/del/issues/83

**Comment by BendingBender** [comment]
I'll look into it when I feel like it.

**Comment by SamVerschueren** [comment]
I might be missing something here, but when I add a new test to `tsd` with the following `d.ts` file

```ts
export type LiteralUnion<
	LiteralType extends BaseType,
	BaseType extends Primitive
> = LiteralType | (BaseType & {_?: never});
```

And a `test-d.ts` file

```ts
import {expectType} from '../../..';
import {LiteralUnion} from '.';

type Pet = LiteralUnion<'dog' | 'cat', string>;

expectType<Pet>('dog');
```

The output becomes

```js
{ 
	fileName: '/Users/sam/Projects/opensource/tsd-check/dist/test/fixtures/missing-import/index.d.ts',
	message: 'Cannot find name \'Primitive\'.',
	severity: 'error',
	line: 3,
	column: 18
}
```

So not sure why it doesn't catch it in for example type-fest 🤔. I'll test it directly in type-fest to see what happens there...

**Comment by SamVerschueren** [comment]
The reason for this was that `@sindresorhus/tsconfig` sets the `skipLibCheck` property to `true`.

From the TS Docs

> Skip type checking of all declaration files (`*.d.ts`).

This means that the TSD compiler does not type check what's inside the `d.ts` file, it only catches the errors in the `test-d.ts` file. I've turned it off by default so now it should work as expected.
