### ISSUE TITLE
what's the purpose of this lib?

### ISSUE THREAD

**Issue by zzzgit** [SamVerschueren/tsd#28]
What's the purpose of this lib?
Is it used to help in developing or in runtime type check?

**Comment by BendingBender** [comment]
From the project title:
> Check TypeScript type definitions

By definition, this can only be compile-time, type definitions aren't present at runtime. More specific, this is for testing type definitions correctness, usually paired with a CI setup.

**Comment by zzzgit** [comment]
Normally, `*.d.ts` files are emitted by `tsc`, is it still need to be tested?

**Comment by BendingBender** [comment]
It's for JS libraries that provide hand-written `*.d.ts` files.

**Comment by zzzgit** [comment]
Okay, thanks

**Comment by fregante** [comment]
> It's for JS libraries that provide hand-written `*.d.ts` files.

Why wouldn't a repo with TS source benefit from `tsd`? Just because TS generates those definitions it doesn't mean that they match your expectations.
