### ISSUE TITLE
Execute test files

### ISSUE THREAD

**Issue by hueniverse** [SamVerschueren/tsd#38]
Just an FYI.

We've recently had some issues with type tests (using lab, but the same logic as tsd) that were passing but still invalid. I added actually loading these files and executing them to ensure they not just pass TS diagnostics. All my code is pure JS. I don't use TS which means I don't have any real TS tests other than the type definitions passed to the tsd-like process.

To solve it, I've added this: https://github.com/hapijs/lab/blob/master/lib/types.js#L178-L226

**Comment by SamVerschueren** [comment]
Just wondering, what are cases where the diagnostics actually don't report anything but running it causes errors?

**Comment by hueniverse** [comment]
When the type definitions match the tests, but the tests and type definitions don't match the actual JS code... Had some issues lately with default exports that didn't match those in JS.

**Comment by hueniverse** [comment]
Just had a case where this was useful.

https://github.com/hapijs/hoek/commit/980cc9cd2de6fb86c6d91a8fe9fc96af5d6d774a

Basically, the js code changed and the ts code testing the types no longer worked when executed.
