### ISSUE TITLE
Inline type definition + type compatibility check

### ISSUE THREAD

**Issue by harrysolovay** [SamVerschueren/tsd#41]
Originally prompted in #37 –– here's a feature request for inlining type compatibility checks with any ts code (doesn't have to be in a standalone file, with `tsd` triggered via its cli command).

A simple example:

```ts
import { expectType } from "tsd";

interface Person {
  name: string;
  friends: Person[];
}

const personA = {
  name: "Joe",
  friends: [personB],
};

const personB = {
  name: "Jack",
  friends: [personA],
};

try {
  expectType<Person>(personA);
} catch(e) {}
```

Internally, `expectType` would get its parent module path (the file from which it is executed) and add it to a shared program instance.

**Comment by harrysolovay** [comment]
One problem I see:

getting the type, inline, is often difficult. Lets say you have a map of objects, each with a `type` key that refers to a constructor, and you iterate through these objects...

```ts
// define the constructor/type we want to compare to
interface Person {
  type: "Person";
  name: string;
  friends: Person[];
}

// place the constructor in a map
const constructors = new Map<string, new () => T>();
constructors.set("Person", Person);

// construct an array of untyped `Person`s
const at = [];
const personA = { type: "Person", name: "Joe", friends: [personB] };
const personB = { type: "Person", name: "Jack", friends: [personA] };
at.push(personA, personB);
```

Now we try to iterate through and type-check our `T` instances according to their specified constructors:

```ts
for (const t of at) {
  const typeKey = t.type;
  const Constructor = constructors.get(typeKey);
  expectType<Constructor>(t); // will break
}
```

The last line will cause a compiler error, as `Constructor` is recognized as a value, but is being used as a type.

The above is happening inside of a loop. Therefore, I'm not so sure that extracting the iteration-specific type info is doable. If the constructor root definition was transformed to append type metadata for runtime use, this would be doable... but it's hacky. Is there a way to enable `tsd` to effectively do its job independent of the type/value dilemma? Otherwise, I kind of understand why one would prefer to limit any programatic usage.

Even if `tsd` took the approach of serializing type info into a runtime validation function, this might be an issue.

Any thoughts?

**Comment by SamVerschueren** [comment]
I'm just wondering what the actual value would be for this? Because the `expectType` calls will also end up in your bundle. Meaning, that it will also ship TypeScript to your users. 

You could already use `expectType` inside your code, if you really want.

```ts
expectType<string>(1);
```

This will cause a compiler error. The things you don't have is strict type assertions for instance, because it needs to run custom validations based upon the type information extracted from the files.

The main goal for `tsd` is to write tests easily for hand written type definitions. Being able to add it to your source files might be out of scope of this project, not sure yet. Let's just keep this open for discussion.

**Comment by SamVerschueren** [comment]
Also, if you are looking into runtime validation, [`ow`](https://github.com/sindresorhus/ow) would be helpful.

**Comment by harrysolovay** [comment]
I can't speak to how others would use it, but I personally want to use it to create a tool that looks at a `type` field on any arbitrary object, and compares it to a corresponding, user-provided type. This is meant to replace the need for type validations via tools like [ow](https://github.com/sindresorhus/ow) or [class-validator](https://github.com/typestack/class-validator).

**One solution would be** to serialize the final object (which may have cycles) into a TypeScript AST, create a new source file out of it (with the user-provided types imported), and then gather the compiler's diagnostics... I don't love this solution, but it may be the only way.

The benefit of this would be that tool-developers could more easily verify user-provided data matches type definitions (either internal or user-provided). Using the type system, instead of a library's own convention, offers a much cleaner DX imo. Your correct in that it would lend `tsd` to a different use case (not sure if you're looking to cover this use case). My best guess is that users would benefit from this ability. After all, a lot of the time, data is gathered dynamically from an untyped source. It would be great to enable the following:

```ts
import { expectType } from "tsd";
import { Person } from "./declarations";
import { fetchMaybePeople } from "./api-client";

(async () => {
  const maybePeople = await fetchMaybePeople();
  const people = Person[];
  const notPeople = [];

  for (const maybePerson of maybePeople) {
    try {
      expectType<Person>(maybePerson);
      people.push(maybePerson);
    } catch(e) {
      notPeople.push(maybePerson);
    }
  }
})();
```

**Comment by SamVerschueren** [comment]
I think this would make a nice library, but I think it's way out of scope of what `tsd` tries to solve right now. It's main focus is to test hand written (or auto-generated) type definitions. The thing that you are asking would be a combination of `ow` and `tsd` where you could do `ow<Person>(maybePerson)` and then at compile time it generates an `ow.object.exactShape` validator out of the provided type definition. This would be very cool, but as I said, pretty out of scope for `tsd` at this point.

**Comment by harrysolovay** [comment]
Completely understandable. Thank you anyways!
