### ISSUE TITLE
How to use `expectType` on a `unique symbol`?

### ISSUE THREAD

**Issue by garyking** [SamVerschueren/tsd#49]
If I have a `declare const item: unique symbol;` and I test it with `expectType<unique symbol>(item);`, it won't work.

For `<Symbol>`, I get `Parameter type Symbol is declared too wide for argument type unique symbol.`. 

Therefore, is it possible to test `unique symbol`?

**Comment by SamVerschueren** [comment]
You can't use `unique symbol` as a type, so it's not possible to do `expectType<unique symbol>(item);` as you said yourself.

As of the next release, you could do `expectAssignable<symbol>(item);`. I don't think we can do any better here unless I'm missing something?

Would that solve your problem? 

The stricter we can validate, the better but `unique symbol` is not allowed to be passed as generic.

https://twitter.com/SamVerschueren/status/1194297033902964737

**Comment by garyking** [comment]
Okay I'll just use `<symbol>` for now.

**Comment by SamVerschueren** [comment]
I'm going to close this (for now) as it's just not possible with TypeScript itself.

**Comment by LinusU** [comment]
@SamVerschueren How about adding a `expectSymbol` function, like so:

```typescript
declare const expectSymbol: <T extends Symbol>(value: T) => void;
```

That way you can check that a specific symbol being exported from a library is 1) actually a Symbol (the `T extends Symbol` part), and 2) that the symbol is indeed being exported.

e.g.

https://github.com/sindresorhus/find-up/blob/7011e0b3afa7d0226ff6aefebe4bb13867f91c11/index.test-d.ts#L77-L78

```typescript
expectSymbol<findUp.StopSymbol>(findUp.stop);
```

also ping @sindresorhus ☺️

**Comment by ExE-Boss** [comment]
It should be:
```ts
declare const expectSymbol: <T extends symbol>(value: T) => void;
```

Because `symbol` primitives don't extend the boxed `Symbol` wrapper object.

**Comment by sindresorhus** [comment]
@LinusU Would `expectSymbol` have any benefits over `expectAssignable<findUp.StopSymbol>(findUp.stop);`?

**Comment by LinusU** [comment]
@sindresorhus yeah, it would check that `findUp.StopSymbol` is actually a symbol, instead of being e.g. a string or number. Maybe that is not super important though... 🤔
