### ISSUE TITLE
Rename the binary to `tsd`?

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/tsd#5]

**Comment by SamVerschueren** [comment]
I filed a support case at npmjs to get hold of the `tsd` package name.

@blakeembrey I saw you in the other thread and noticed that you are one of the co-authors of the `tsd` package :).

**Comment by SamVerschueren** [comment]
Jeeej, this finally happened!!!! 🎉🎉🎉🎉🎉🎉🎉

**Comment by sindresorhus** [comment]
// @BendingBender FYI => https://github.com/SamVerschueren/tsd/releases/tag/v0.7.0
