### ISSUE TITLE
Ability to assert a property doesn't exist?

### ISSUE THREAD

**Issue by yyx990803** [SamVerschueren/tsd#50]
First of all, thank you very much for creating this utility! This is very useful for lib authors and I think it it something that TS should consider adopting as built-in.

Currently, `expectError` only asserts function argument type errors, and "property does not exist" errors are suppressed. This causes any missing property to have type `any` and will be passable to any function:

``` js
// assuming foo.bar does not exist, this will result in "Expected an error, but found none."
expectError(someFunc(foo.bar))
```

`expectType<never>(foo.bar)` also doesn't work because missing property defaults to `any` instead of `never`.

I am not entirely sure if it's a limitation of `tsd` or there is a simple way of doing this. Any insight is appreciated!

**Comment by yyx990803** [comment]
Never mind - it seems to be working now!

**Comment by SamVerschueren** [comment]
Thank you!

No problem! If I can be of any assistance, feel free to create an issue or send a DM. Happy to help :).
