### ISSUE TITLE
Errors when type definition path is a subpath of a file in `files`

### ISSUE THREAD

**Issue by posva** [SamVerschueren/tsd#57]
If the type definition file is in a subfolder of a path included in `files`, `tsd` will error this message:

```
package.json:25:2
  ✖  25:2  TypeScript type definition dist/src is not part of the files list.
```

sample `package.json` file:

```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "types": "dist/src",
  "files": ["dist"],
  "license": "MIT",
  "devDependencies": {
    "tsd": "^0.11.0"
  }
}
```

Creating an empty file `dist/src/index.d.ts` alongside this package.json file should be enough to reproduce it 🙂 

As a workaround, including `dist/src` in `files` works just fine

**Comment by SamVerschueren** [comment]
Thanks for posting this. Will have a look :).

**Comment by szmarczak** [comment]
@SamVerschueren Friendly ping :) This is quite annoying because I cannot put the declarations file in the `source` folder...

**Comment by SamVerschueren** [comment]
I'll see if I can fix this. Shouldn't be that hard.

**Comment by SamVerschueren** [comment]
So I looked into this, and this is already fixed somewhat, see #69 for more information. For instance, the following `package.json` works.

```json
{
	"name": "foo",
	"files": [
		"out"
	],
	"types": "out/index.d.ts"
}
```

What doesn't work however, is this

```json
{
	"name": "foo",
	"files": [
		"out"
	],
	"types": "out"
}
```

When looking at the specs of the `types` property, it doesn't seem to be meant to provide a directory. So just changing `types` to `out/index.d.ts` should work.

Does this fix the issue for both of you @szmarczak and @posva?

**Comment by SamVerschueren** [comment]
I'm going to close this, feel free to create a new issue or ask me to reopen it if it's not working as expected.

**Comment by szmarczak** [comment]
Yep, it's working as expected. Sorry I haven't told you before, I totally forgot :see_no_evil:
