### ISSUE TITLE
Can't expect type on a type intersection

### ISSUE THREAD

**Issue by Ethan-Arrowood** [SamVerschueren/tsd#59]
I'm getting this error message from my unit test:
```
Parameter type HeadersType is declared too wide for argument type IncomingHttpHeaders & HeadersType.
```
I understand this has something to do with `expectType` being is strict mode (#40). Can you please share how I could improve my type check here? Should I use something other than void? 

The type definition (simplified)
```typescript
interface CustomHeaders<G> {
  headers: http.IncomingHttpHeaders & G
}
```

And my test implementation (simplified)
```typescript
type HeadersType = { prop: string }
const req: CustomHeaders<HeadersType> = { headers: { prop: 'Header' } }
expectType<HeadersType>(obj.headers)
```

I made a [typescript playground](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJIAkJwCbQM7IDeAUMmcgOQwD21FA-AFzJ5hSgDmANKeRQEZwoDZq3YgOxAL7FioSLEQpUAYQCuragFtomHPgA8AcQB8RXmQAWWXFDzMMN-MgBkyI9NlgAngAcUerZ4ACp+KAC8RJQwagBesRSibJzIMsQI1CCsyGCWnA7qmjpQgYaldqH+ZpEk5MjW+nbMtXXkMfHMAnEJFqnSQA) that implements this pattern so I don't know why its failing in TSD

**Comment by Ethan-Arrowood** [comment]
If you want to see the whole example / where I discovered this issue checkout the reference issue ^^ from the Fastify library

**Comment by ExE-Boss** [comment]
You&nbsp;need to&nbsp;call:
```ts
expectType<http.IncomingHttpHeaders & HeadersType>(obj.headers);
```

**Comment by Ethan-Arrowood** [comment]
Thank you @ExE-Boss
