### ISSUE TITLE
expectType problem

### ISSUE THREAD

**Issue by belozer** [SamVerschueren/tsd#60]
I'am try using tsd for write library tests. But something is not correct.

See example (`line #7`):

![image](https://user-images.githubusercontent.com/1655916/69652952-7fda6200-1083-11ea-9994-f558f9141fb7.png)

Project repo
https://github.com/artalar/reatom

Where did I make a mistake?

**Comment by sindresorhus** [comment]
`{foo: 'aa'}` is not the same type as `{foo: 'bar'}`.

**Comment by belozer** [comment]
@sindresorhus `line #9` is ok. Please see `line #7`

**Comment by sindresorhus** [comment]
What error are you getting?

**Comment by belozer** [comment]
> What error are you getting?

I expect to get an error because the types are different.

```
Atom<string> !== Atom<number>
```

But instead I don't get any error.

**Comment by belozer** [comment]
Hmm... It seems that the problem is not in tsd.
