### ISSUE TITLE
expectNotAssignable doesn't error when the type is assignable

### ISSUE THREAD

**Issue by iansan5653** [SamVerschueren/tsd#65]
I am trying to use `dst`'s functions to help test my type utilities with Jest. I have a test where I want to make sure that the result is _not_ assignable to the expected type, so of course I want to use the `expectNotAssignable` method. However, this does not error in Jest, even when the type and value are obviously assignable.

For example,  this test should fail but it passes:
```ts
test("string is not assignable to string", () => {
  expectNotAssignable<string>("example");
});
```

**Comment by papb** [comment]
Hello! I am another user quite lost with the usage of tsd, but I think I figured something out already: tsd is not supposed to be used like that, as a dependency that you include and call normally...

What you should be doing apparently is creating a `.test-d.ts` file and then calling [`await tsd({ cwd: 'path/to/folder/containing/your/test/file.test-d.ts' })`](https://github.com/SamVerschueren/tsd#programmatic-api), which seems to be the only api that really works "normally".

Take a look at my guesses at #66

**Comment by SamVerschueren** [comment]
Like @papb mentions, it cannot be used inside regular tests. `tsd` is meant to test type definitions or typings, separate from your business logic. It uses the AST to validate the assertions, and can't be done at runtime. So you will have to run `tsd` either with the CLI tool or like @papb mentions with the programmatic API as defined here https://github.com/SamVerschueren/tsd#programmatic-api.

You can see an example of `expectNotAssignable` usage in the tests here https://github.com/SamVerschueren/tsd/tree/master/source/test/fixtures/assignability/not-assignable.

**Comment by SamVerschueren** [comment]
Going to close this as I think it's not used for what `tsd` is meant to do.

**Comment by papb** [comment]
@iansan5653 You could also use the [expect-type](https://www.npmjs.com/package/expect-type) package which can be used exactly how you tried to use `tsd`.
