### ISSUE TITLE
Why bidirectional assignability is not equivalent to identicality?

### ISSUE THREAD

**Issue by papb** [SamVerschueren/tsd#67]
This might be a lack of deeper understanding on how TypeScript really works, but:

* `index.d.ts`

  ```ts
  export declare type Foo = { foo: string; };
  export declare type Bar = { bar: number; };
  export declare type FooBar1 = Foo & Bar;
  export declare type FooBar2 = { foo: string; bar: number; };
  export declare const foobar1: FooBar1;
  export declare const foobar2: FooBar2;
  ```

* `index.test-d.ts`

  ```ts
  import { expectType, expectAssignable } from 'tsd';
  import { FooBar1, FooBar2, foobar1, foobar2 } from '.';
  
  expectAssignable<FooBar1>(foobar1); // ok
  expectAssignable<FooBar1>(foobar2); // ok
  expectAssignable<FooBar2>(foobar1); // ok
  expectAssignable<FooBar2>(foobar2); // ok
  
  expectType<FooBar1>(foobar2); // not ok
  expectType<FooBar2>(foobar1); // not ok
  ```

Is this a bug on `tsd` or a bug on my understanding of TypeScript?

Regardless, I think a clarification for this might be useful for many people (so consider this a suggestion part of #55)

Thanks in advance!

**Comment by papb** [comment]
Bonus (and note to self):

```ts
type Foo = { foo: string };
type Bar = { bar: number };

export type FooBar1 = Foo & Bar;
export type FooBar2 = { foo: string; bar: number };
export interface FooBar3 extends Foo, Bar {}
export interface FooBar4 extends FooBar1 {}
export interface FooBar5 extends FooBar2 {}
export interface FooBar6 extends Foo { bar: number }
export interface FooBar7 extends Bar { foo: string }
export interface FooBar8 { foo: string, bar: number }
```

With `tsd` I found that:

* All 8 exported types (`FooBar1` until `FooBar8`) are bidirectionally assignable to each other (checked via `expectAssignable`)
* Types `FooBar2` until `FooBar8` are identical to each other (checked via `expectType`)
* Type `FooBar1` is not identical to any of the other exported types (`FooBar2` until `FooBar8`)  (checked via `expectType`)

So I am starting to believe this is probably a misunderstanding of TypeScript by me.

**Comment by SamVerschueren** [comment]
More information can be found here. https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.11.2

- they are both the Any type,
- they are the same primitive type,
- they are the same type parameter,
- they are union types with identical sets of constituent types, or
- they are intersection types with identical sets of constituent types, or
- they are object types with identical sets of members.

In this use case, the last two bullet points apply:

- they are intersection types with identical sets of constituent types, or
- they are object types with identical sets of members.

In case of `FooBar1`, we have an intersection type. Two types are identical if they both are an intersection type with the same end result. But in your use case, you have an intersection type and an object type and TS doesn't think they are identical.

Meaning, if you do this instead

```ts
export declare type Foo = { foo: string; };
export declare type Bar = { bar: number; };
export declare type Baz = { bar: number; };
export declare type FooBar1 = Foo & Bar;
export declare type FooBar2 = Foo & Baz;
```

`FooBar1` and `FooBar2` are considered identical. You wil have to ask the TS team themselves why they can't be considered identical, `tsd` just uses the TS APIs under the hood to verify both types.

I hope this answers your question?

**Comment by SamVerschueren** [comment]
I'm closing this as I believe I answered your question and I want to reduce the number of open issues :).
