### ISSUE TITLE
False positive: TypeScript type definition dist\index.d.ts is not part of the files list

### ISSUE THREAD

**Issue by Lusito** [SamVerschueren/tsd#69]
Currently digging into your tool and I got the above error.
I have the whole folder included:

```json
"files": [
    "dist"
  ],
```

**Comment by papb** [comment]
Looks like [it is](https://github.com/SamVerschueren/tsd/blob/master/package.json#L28) included... Can you clarify what you mean?

**Comment by Lusito** [comment]
Sorry, I guess that was a bit unclear: I am running TSD on my project and it complains about my package.json, where I do have the whole directory included in the files part.

I.e. the check TSD does not cover the case of directories being specified in the files array. It assumes you specify your files one by one, which is ridiculous for some projects.

**Comment by AndrewLeedham** [comment]
I am also seeing this. Would be great to see it included :)
