### ISSUE TITLE
Catch missing lib imports

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/tsd#7]
For example, if a library that targets both Node.js and the browser uses a DOM-only global, it should do what's done here: https://github.com/sindresorhus/delay/commit/875441b3933b4881cd8d01bc156b06c802865e1f

Would be nice if `tsd-check` could catch cases like these.

Same with using a ES2018 global.

**Comment by SamVerschueren** [comment]
This would be nice! How do you think this should be resolved? Should it auto-add the reference? Should it just throw a warning?

**Comment by sindresorhus** [comment]
> Should it just throw a warning?

👍 I think we should keep `tsd-check` a read-only tool, at least for now.

**Comment by BendingBender** [comment]
Just tried it out quick-and-dirty style, seems that this can be fixed by explicitly specifying the `lib` config option. Explicitly setting it to
```js
lib: [
	'es2017'
],
```
produces the desired result. I can add it to #18, if you're OK with that.

**Comment by SamVerschueren** [comment]
Why does that solve the issue? Wouldn't that mean if we use some feature from `es2018` or `dom` it still doesn't work?

**Comment by BendingBender** [comment]
Like this we would default to `es2017`. If we don't specify the `lib` config option, TS chooses following as default:
```
["dom", "es6", "dom.iterable", "scripthost"]
```
which is why currently a usage of a type from `dom` library is not reported.

**Comment by SamVerschueren** [comment]
But isn't the point of adding the triple-slash-reference that if I install module A, I don't have to manually add the `dom` lib for instance to my config because module A needs it for its typings?

**Comment by BendingBender** [comment]
You have a point here. But I'm not sure what you propose instead.

`tsd-check` will flag an issue if a triple-slash reference is missing. Adding one will fix the error. Sounds like desirable behavior.

**Comment by BendingBender** [comment]
And I suppose that some people will want to set the `lib` field in the config, whether we should support this is debatable.
