### ISSUE TITLE
TypeScript 3.9 support

### ISSUE THREAD

**Issue by mkrause** [SamVerschueren/tsd#71]
Is this project still maintained? Looks like the TypeScript compiler is currently stuck at v3.7. This is starting to cause issues as some packages are starting to adopt newer TS syntax. For example, I cannot upgrade to the latest version of `pretty-format` without breaking `tsd`, because it uses `import type` syntax in its definitions:

https://github.com/facebook/jest/blob/master/packages/pretty-format/src/index.ts

**Comment by papb** [comment]
I am also waiting for feedback in some questions I raised in this repository... In the meantime, I have been using [expect-type](https://www.npmjs.com/package/expect-type). It's a very different approach, and I like it so far.

**Comment by SamVerschueren** [comment]
Yes, I'm planning to upgrade in the coming days.

**Comment by SamVerschueren** [comment]
Released as `0.13.0`.

**Comment by mkrause** [comment]
Thank you!
