### ISSUE TITLE
does not catch `never` type

### ISSUE THREAD

**Issue by dgreene1** [SamVerschueren/tsd#78]
**Expected Behavior:**

I would expect the following to fail. It does not.
```ts
const result: never = () => { throw new Error() };

expectType<string>(result);
```

**Comment by BendingBender** [comment]
@dgreene1 @fregante @sindresorhus I've tried to reproduce this issue in the latest version of `tsd` without success. Can you please confirm that the latest version of `tsd` is not affected by this?

**Comment by JGJP** [comment]
@BendingBender 
I can confirm that the latest version of `tsd` is affected by this. The original example needed some amending though:

```ts
const returnsNever = () => { throw new Error() };
const result: never = returnsNever()
expectType<string>(result)
```

**Comment by JGJP** [comment]
@BendingBender 
This fails appropriately when using `ts-expect`:

```ts
expectType<TypeEqual<string, never>>(true)
```
