### ISSUE TITLE
Erroneous error when index.d.ts is included in the files list as "/index.d.ts"

### ISSUE THREAD

**Issue by chocolateboy** [SamVerschueren/tsd#79]
**tsd**: 0.13.1 | **Node.js**: v14.9.0 | **OS**: Linux (Arch)

I have a `files` array which includes `"/index.d.ts"`, e.g.:

```json
{
    "files": [
        "dist/index.esm.js",
        "dist/index.js",
        "/index.d.ts"
    ]
}
```

The leading slash is needed to include the `index.d.ts` file in the package's root directory and to exclude other files of the same name, e.g. in the `dist` directory (an unqualified `"index.d.ts"` pattern matches *all* files with that name).

tsd is not picking this up and is failing with an error:

> TypeScript type definition index.d.ts is not part of the files list.

The error goes away if the forward slash is removed.

**Comment by fregante** [comment]
I'm guessing the correct way would be to use `./index.d.ts` since `/` might mean the root of your system volume.

**Comment by chocolateboy** [comment]
The [documentation]() says "file patterns follow a similar syntax to .gitignore". In [`.gitignore`](https://git-scm.com/docs/gitignore), forward slash just means directory separator:

> The slash / is used as the directory separator. Separators may occur at the **beginning**, middle or end of the .gitignore search pattern.

**Comment by fregante** [comment]
Regardless of documentation (which says "similar", but doesn't commit to the same exact format), I confirm that npm@6.14.5 also includes files starting with a slash.
