### ISSUE TITLE
rootDir is expected to contain all source files

### ISSUE THREAD

**Issue by caseyWebb** [SamVerschueren/tsd#80]
tsd blows up when using compilerOptions.rootDir in tsconfig.json

__tsconfig.json__
```json
{
  "compilerOptions": {
    "incremental": true,
    "target": "es5",
    "lib": ["es2015", "es2019.array"],
    "declaration": true,
    "sourceMap": true,
    "inlineSources": true,
    "rootDir": "./src",
    "importHelpers": true,
    "strict": true,
    "alwaysStrict": true,
    "moduleResolution": "node",
    "esModuleInterop": true
  },
  "exclude": ["**/dist/**", "**/test/**"]
}

```

```
 src/utils.ts:6:7
  ✖  6:7   File /home/casey/code/badbadnotgood/src/validators.ts is not under rootDir tsconfig.json/src. rootDir is expected to contain all source files. 
```

**Comment by BendingBender** [comment]
@caseyWebb @rivy @hoeck I've tried to reproduce this issue with the current version of `tsd` (0.16.0) without success. Could you please provide additional information? I'd need the `tsd` config from your `package.json`. And it would be great if you could try to reproduce the issue with your setup and give feedback this problem still occurs with the current version of `tsd`?

**Comment by hoeck** [comment]
I've pushed a failing case to https://github.com/hoeck/simple-runtypes/tree/tsd-root-dir-test

It contains the tsd configuration in package.json and is using 0.16. When installing everything (using still yarn1) and then running `node_modules/.bin/tsd` I get lots of errors such as

```

**Comment by BendingBender** [comment]
@hoeck Thank you, it was very helpful. Would you mind to test my PR #117 in your project?

**Comment by hoeck** [comment]
Great, of course I'll do that! It might take me until tomorrow to send you any feedback though bc. my schedule is full.

**Comment by hoeck** [comment]
@BendingBender just tried the master branch of tsd, the error is gone, it is working as expected yay :100: :smile:. Thanks for fixing this will make my package builds a little bit less complex.

**Comment by BendingBender** [comment]
Good to hear that. The patch is now part of the 0.17.0 release, you can simply upgrade`tsd` to get this fix.
