### ISSUE TITLE
How to add failing tests?

### ISSUE THREAD

**Issue by fregante** [SamVerschueren/tsd#81]
Like [in AVA](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests):

> You can use the `.failing` modifier to document issues with your code that need to be fixed

How can I add an expectation that is currently failing? I thought I could use `@ts-expect-error` but this is just ignored:

```ts
  test-d/index.test-d.ts:38:2
  ✖  37:2  Unused @ts-expect-error directive.                            
  ✖  38:2  Parameter type string is not identical to argument type any.  

  2 errors
```

**Comment by BendingBender** [comment]
Can you please explain why `expectError` isn't sufficient for your use case?
