### ISSUE TITLE
Does not catch `any` type

### ISSUE THREAD

**Issue by fregante** [SamVerschueren/tsd#82]
Similarly to #78, `expectType` doesn't seem to catch… `any`

All of this passes:

```ts
import {expectType} from 'tsd';
expectType<false>('' as any);
expectNotType<false>('' as any);
expectNotType<any>('' as any);
```

```json
{
	"tsd": "^0.13.1",
	"typescript": "^4.0.3"
}
```

**Comment by papb** [comment]
In the mean time you can use [`expect-type`](https://www.npmjs.com/package/expect-type) for this

**Comment by SamVerschueren** [comment]
I believe I do a check to see if the generic type isn't declared too wide, for example

```ts
expectType<any>(true);
//=> Parameter type `any` is declared too wide for argument type `true`
```

But I don't think I do it the other way around 🤔 .

**Comment by BendingBender** [comment]
@fregante @sindresorhus @papb I've tried to reproduce this issue in the latest version of `tsd` without success. Can you please confirm that the latest version of `tsd` is not affected by this?
