### ISSUE TITLE
Add a function that outputs the exact type

### ISSUE THREAD

**Issue by jandockx** [SamVerschueren/tsd#90]
During debugging the `d.ts` files, it is often helpful to see the type TS inferred.

Now, I do this by writing temporarily

```ts
expectType<string>(expressionOfAComplexType)
```

This fails, and in the error message we see the type TS inferred, e.g.:

```
Argument of type { <T>(this: T, thisArg: any): T; <A0, A extends any[], R>(this: new (arg0: A0, ...args: A) => R, thisArg: any, arg0: A0): new (...args: A) => R; <A0, A1, A extends any[], R>(this: new (arg0: A0, arg1: A1, ...args: A) => R, thisArg: any, arg0: A0, arg1: A1): new (...args: A) => R; <A0, A1, A2, A extends any[], R>(thi... is not assignable to parameter of type string.
```

That helps for "not to complex" types. But, as you can see, when the type becomes more complex, the output is shortened with ellipsis.

It would be nice to have a `printType` that we could use like

```ts
printType(expressionOfAComplexType)
```

that would print the complete type to stdout.

**Comment by BendingBender** [comment]
@jandockx @sindresorhus @papb Would you mind testing [my PR](https://github.com/SamVerschueren/tsd/pull/115) whether it is the helpful or whether something is missing?
