### ISSUE TITLE
Any reason for pinning the old version of Meow? Vulnerabilities

### ISSUE THREAD

**Issue by cgalememx** [SamVerschueren/tsd#98]
Okta auth is using your lib and the old dependency subtree is throwing a lot of vulnerability warnings:

├─┬ @okta/okta-auth-js@4.9.0
│ └─┬ tsd@0.14.0
│   └─┬ meow@7.1.1
│     └─┬ normalize-package-data@2.5.0
│       └── hosted-git-info@2.8.9

**Comment by BendingBender** [comment]
This is actually quite strange, I don't get any vulnerability warnings from `npm` when installing `tsd`.

![screenshot](https://user-images.githubusercontent.com/4807083/119893208-61387e00-bf3b-11eb-8096-8aa1f4500f9e.png)
