### ISSUE TITLE
`expectType` is not compatible with `@typescript-eslint/no-unsafe-call`

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/tsd#99]
It's causing a lint error:

```ts
import {expectType} from 'tsd';
import normalizeNewline from './index.js';

expectType<string>(normalizeNewline('foo\r\nbar\nbaz'));
```

```
❯ xo

  index.test-d.ts:4:1
  ✖  4:1  Unsafe call of an any typed value.  @typescript-eslint/no-unsafe-call
```

**Comment by SamVerschueren** [comment]
Is this a bug in the rule? Because `expecType` is typed correctly and if I add it to the code directly, like this, it just works.

```ts
import normalizeNewline from './index.js';

declare const expectType: <T>(value: T) => void;

expectType<string>(normalizeNewline('foo\r\nbar\nbaz'));
```

So I'm wondering what could actually cause this 🤔 .

**Comment by BendingBender** [comment]
@sindresorhus I tried to reproduce this with the current version of `eslint`, without any success. See #120. Do you still have this problem with one of your projects?
